server.modules = ("mod_accesslog", "mod_indexfile")

server.document-root = "/config/local-www"
server.port = 8099
server.bind = "0.0.0.0"

index-file.names = ( "index.html", "index.htm" )

mimetype.assign = (
  ".html" => "text/html",
  ".css"  => "text/css",
  ".js"   => "application/javascript",
  ".json" => "application/json",
  ".png"  => "image/png",
  ".jpg"  => "image/jpeg",
  ".svg"  => "image/svg+xml",
  ".ico"  => "image/x-icon",
  ".woff2" => "font/woff2"
)

accesslog.filename = "/proc/1/fd/1"
server.errorlog    = "/proc/1/fd/2"
